In [26]:
import pandas as pd
import numpy as np
import sqlite3
import time

In [2]:
trips = pd.read_csv('../../CSVs/trips.csv', low_memory=False)
stop_times = pd.read_csv('../../CSVs/stop_times.csv', low_memory=False)
#st_update = pd.read_csv('../../CSVs/stop_time_updates.csv', usecols=['stop_sequence', 'arrival_time', 'trip_update_id'], low_memory=False)
trp_update = pd.read_csv('../../CSVs/trip_updates.csv', usecols=['trip_id', 'route_id', 'timestamp', 'trip_start_time'], low_memory=False)

In [3]:
trp_update.head()

trip_id route_id  trip_start_time                   timestamp
0  35242107        1              NaN  2017-09-25 22:33:24.000000
1  35242108        1              NaN  2017-09-25 22:33:24.000000
2  35242109        1              NaN  2017-09-25 22:33:24.000000
3  35242110        1              NaN  2017-09-25 22:33:24.000000
4  35242111        1              NaN  2017-09-25 22:33:24.000000

In [4]:
stop_times = stop_times.loc[:, ['trip_id', 'stop_id', 'stop_sequence', 'arrival_time', 'departure_time']]
stop_times.head()

trip_id                stop_id  stop_sequence arrival_time  \
0  Logan-22-Weekday-trip           Logan-Subway              1     08:00:00   
1  Logan-22-Weekday-trip  Logan-RentalCarCenter              2     08:04:00   
2  Logan-22-Weekday-trip                Logan-A              3     08:09:00   
3  Logan-22-Weekday-trip                Logan-B              4     08:12:00   
4  Logan-22-Weekday-trip           Logan-Subway              5     08:17:00   

  departure_time  
0       08:00:00  
1       08:04:00  
2       08:09:00  
3       08:12:00  
4       08:17:00

In [5]:
trips = trips.loc[:, ['trip_id', 'route_id', 'service_id', 'trip_headsign']]
trips.head()

trip_id  route_id     service_id trip_headsign
0  Logan-22-Weekday-trip  Logan-22  Logan-Weekday          Loop
1  Logan-22-Weekend-trip  Logan-22  Logan-Weekend          Loop
2  Logan-33-Weekday-trip  Logan-33  Logan-Weekday          Loop
3  Logan-33-Weekend-trip  Logan-33  Logan-Weekend          Loop
4  Logan-55-Weekday-trip  Logan-55  Logan-Weekday          Loop

Obtain all the first stops for all trips as well as their expected arrival time.

In [6]:
first_stops = stop_times.loc[stop_times['stop_sequence'] == 1, :]
first_stops.head()

trip_id       stop_id  stop_sequence arrival_time  \
0   Logan-22-Weekday-trip  Logan-Subway              1     08:00:00   
7   Logan-22-Weekend-trip  Logan-Subway              1     12:00:00   
14  Logan-33-Weekday-trip  Logan-Subway              1     08:00:00   
21  Logan-33-Weekend-trip  Logan-Subway              1     12:00:00   
28  Logan-55-Weekday-trip  Logan-Subway              1     00:00:00   

   departure_time  
0        08:00:00  
7        12:00:00  
14       08:00:00  
21       12:00:00  
28       00:00:00

In [14]:
[trp_update['timestamp'].min(),trp_update['timestamp'].max()]

['2017-09-25 22:33:24.000000', '2017-09-26 12:33:39.000000']

Above is the time the first update and last update were obtained. Now to find trips that are running around the same time real time data was being gathered.

In [16]:
first_stops[first_stops['arrival_time'] == '21:00:00'][:25]

trip_id        stop_id  stop_sequence  \
1662    CR-Saturday-October-17-L-1314         Lowell              1   
1790     CR-Saturday-August-17-L-1314         Lowell              1   
3591       CR-Saturday-Spring-17-1160    Newburyport              1   
4691      CR-Sunday-October-17-L-2314         Lowell              1   
4819       CR-Sunday-August-17-L-2314         Lowell              1   
6313         CR-Sunday-Spring-17-2160    Newburyport              1   
8845         CR-Weekday-Spring-17-530      Worcester              1   
9852         CR-Weekday-Spring-17-727  South Station              1   
10267        CR-Weekday-Spring-17-784      Readville              1   
10275        CR-Weekday-Spring-17-785  South Station              1   
63361                        34662072          70106              1   
80125                        34663362          70276              1   
136157                       34670577          70106              1   
176459                       34683277          70038              1   
179195                       34683518          70038              1   
193823                       34685501          70038              1   
194903                       34686454          70276              1   
203937                       34693833          70106              1   
277852                       34849832           3824              1   
281625                       34849906           4275              1   
289596                       34850058          32004              1   
309184                       34850694          32004              1   
320504                       34871357           3582              1   
349466                       34871926            323              1   
371290                       34873363          32004              1   

       arrival_time departure_time  
1662       21:00:00       21:00:00  
1790       21:00:00       21:00:00  
3591       21:00:00       21:00:00  
4691       21:00:00       21:00:00  
4819       21:00:00       21:00:00  
6313       21:00:00       21:00:00  
8845       21:00:00       21:00:00  
9852       21:00:00       21:00:00  
10267      21:00:00       21:00:00  
10275      21:00:00       21:00:00  
63361      21:00:00       21:00:00  
80125      21:00:00       21:00:00  
136157     21:00:00       21:00:00  
176459     21:00:00       21:00:00  
179195     21:00:00       21:00:00  
193823     21:00:00       21:00:00  
194903     21:00:00       21:00:00  
203937     21:00:00       21:00:00  
277852     21:00:00       21:00:00  
281625     21:00:00       21:00:00  
289596     21:00:00       21:00:00  
309184     21:00:00       21:00:00  
320504     21:00:00       21:00:00  
349466     21:00:00       21:00:00  
371290     21:00:00       21:00:00

In [19]:
trp_update[trp_update['trip_id'] == '34663362'].head()

trip_id  route_id  trip_start_time                   timestamp
196427  34663362  Mattapan              NaN  2017-09-26 01:01:39.000000
197029  34663362  Mattapan              NaN  2017-09-26 01:02:13.000000
197620  34663362  Mattapan              NaN  2017-09-26 01:03:54.000000
198215  34663362  Mattapan              NaN  2017-09-26 01:04:27.000000
198809  34663362  Mattapan              NaN  2017-09-26 01:05:01.000000

In [22]:
stop_times[stop_times['trip_id'] == '34663362']

trip_id stop_id  stop_sequence arrival_time departure_time
80125  34663362   70276              1     21:00:00       21:00:00
80126  34663362   70274              2     21:01:00       21:01:00
80127  34663362   70272              3     21:02:00       21:02:00
80128  34663362   70270              4     21:03:00       21:03:00
80129  34663362   70268              5     21:04:00       21:04:00
80130  34663362   70266              6     21:05:00       21:05:00
80131  34663362   70264              7     21:07:00       21:07:00
80132  34663362   70262              8     21:08:00       21:08:00

Above is the expected arrival times for trip 34663362

In [8]:
# connect to the sqlite database for querying data from stop time updates
conn = sqlite3.connect('../../gtfs.db')

In [23]:
first_update = pd.read_sql_query('select * from stop_time_updates where trip_update_id = 196427', conn)
first_update

oid  stop_sequence stop_id  arrival_delay  arrival_time  \
0  4473568              1   70261              0    1506388335   
1  4473569              2   70263              0    1506388393   
2  4473570              3   70265              0    1506388503   
3  4473571              4   70267              0    1506388584   
4  4473572              5   70269              0    1506388671   
5  4473573              6   70271              0    1506388779   
6  4473574              7   70273              0    1506388856   
7  4473575              8   70275              0    1506388946   

   arrival_uncertainty  departure_delay  departure_time  \
0                    0                0      1506388335   
1                    0                0      1506388393   
2                    0                0      1506388503   
3                    0                0      1506388584   
4                    0                0      1506388671   
5                    0                0      1506388779   
6                    0                0      1506388856   
7                    0                0      1506388946   

   departure_uncertainty schedule_relationship  trip_update_id  
0                      0             SCHEDULED          196427  
1                      0             SCHEDULED          196427  
2                      0             SCHEDULED          196427  
3                      0             SCHEDULED          196427  
4                      0             SCHEDULED          196427  
5                      0             SCHEDULED          196427  
6                      0             SCHEDULED          196427  
7                      0             SCHEDULED          196427

We can see that for the first update we the predicted arrival times for all the stops in trip 34663362. Lets look at the predicted arrival times from the second update (trip_update_id = 197029)

In [24]:
second_update = pd.read_sql_query('select * from stop_time_updates where trip_update_id = 197029', conn)
second_update

oid  stop_sequence stop_id  arrival_delay  arrival_time  \
0  4486918              1   70261              0    1506388339   
1  4486919              2   70263              0    1506388397   
2  4486920              3   70265              0    1506388507   
3  4486921              4   70267              0    1506388588   
4  4486922              5   70269              0    1506388675   
5  4486923              6   70271              0    1506388783   
6  4486924              7   70273              0    1506388860   
7  4486925              8   70275              0    1506388950   

   arrival_uncertainty  departure_delay  departure_time  \
0                    0                0      1506388339   
1                    0                0      1506388397   
2                    0                0      1506388507   
3                    0                0      1506388588   
4                    0                0      1506388675   
5                    0                0      1506388783   
6                    0                0      1506388860   
7                    0                0      1506388950   

   departure_uncertainty schedule_relationship  trip_update_id  
0                      0             SCHEDULED          197029  
1                      0             SCHEDULED          197029  
2                      0             SCHEDULED          197029  
3                      0             SCHEDULED          197029  
4                      0             SCHEDULED          197029  
5                      0             SCHEDULED          197029  
6                      0             SCHEDULED          197029  
7                      0             SCHEDULED          197029

On the second update we still have the predicted arrival times for all the stops. Lets compare the predicted arrival time from the first and second update. Their epoch times differ, but lets get a more human readable format.

In [27]:
time.strftime('%Y-%m-%d %H:%M:%S', time.localtime(first_update['arrival_time'][0]))

'2017-09-25 20:12:15'

In [28]:
time.strftime('%Y-%m-%d %H:%M:%S', time.localtime(second_update['arrival_time'][0]))

'2017-09-25 20:12:19'

The predicted arrival times for the first sequence don't differ by much just 4 seconds

In [33]:
third_update = pd.read_sql_query('select * from stop_time_updates where trip_update_id = 198809', conn)
third_update

oid  stop_sequence stop_id  arrival_delay  arrival_time  \
0  4526145              1   70261              0    1506388296   
1  4526146              2   70263              0    1506388354   
2  4526147              3   70265              0    1506388464   
3  4526148              4   70267              0    1506388545   
4  4526149              5   70269              0    1506388632   
5  4526150              6   70271              0    1506388740   
6  4526151              7   70273              0    1506388817   
7  4526152              8   70275              0    1506388907   

   arrival_uncertainty  departure_delay  departure_time  \
0                    0                0      1506388296   
1                    0                0      1506388354   
2                    0                0      1506388464   
3                    0                0      1506388545   
4                    0                0      1506388632   
5                    0                0      1506388740   
6                    0                0      1506388817   
7                    0                0      1506388907   

   departure_uncertainty schedule_relationship  trip_update_id  
0                      0             SCHEDULED          198809  
1                      0             SCHEDULED          198809  
2                      0             SCHEDULED          198809  
3                      0             SCHEDULED          198809  
4                      0             SCHEDULED          198809  
5                      0             SCHEDULED          198809  
6                      0             SCHEDULED          198809  
7                      0             SCHEDULED          198809